### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by SimpleSamples** [bahamas10/node-netscape-bookmarks#4]
How/where is this used? Is it a browser extension? I see the "console.log" in the sample code so I assume this is for use in a browser but I don't understand how it is used other than in a browser.

**Comment by bahamas10** [comment]
This is not for a browser - it's for use by [Node.JS](https://nodejs.org) as a module.  You can see the examples directory for an example usage of this module on the command line.

**Comment by SimpleSamples** [comment]
I see nothing anywhere saying Node.JS. It would really help people looking for software to state explicitly this is _for use by nodejs.org as a module_.

**Comment by bahamas10** [comment]
I tend to start all modules with `node-` (like this module name) when it's intended to be used by `node`, however I'll add a note to the readme.

With some slightly modifications (basically, replace the instances where the `util` module is used) this could be made to work in the browser.
